name: Update README

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Replace Current Tables with New Tables')"

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Copy TEMPLATE to README
        run: |
          cp TEMPLATE.md README.md

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt

      - name: Run src/replace-tables.py
        run: python src/replace-tables.py
      
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Replace Current Tables with New Tables
