name: Update README

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Replace Current Tables with New Tables')"

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt

      - name: Run src/replace-tables.py
        run: python src/replace-tables.py
      
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Replace Current Tables with New Tables
          branch: main
          push_options: '--force'

      - name: Merge main to publish
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: publish
          message: Merge main to publish branch
          github_token: ${{ secrets.GH_TOKEN }}

